version: "3"
services: 
  mymongo:
    build: 
      context: .
      dockerfile: Dockerfile.db

  mynode:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8000:8000"
    depends_on: 
      - "mymongo"